/**
 * ChannelWorkspace — the MIDDLE + RIGHT columns of the three-column conversation
 * workspace (the LEFT customer-info column stays in DetailShell).
 *
 * DEMO ONLY. Given a channel, it renders the matching conversation surface in the
 * middle and a hardcoded AI recommendation on the right, wiring "Use this …" so
 * the suggested text drops into the middle surface. Owns its own local draft
 * state; mounted with key={channel} so switching channels resets it.
 */
import { useState } from 'react'
import type { Channel, Customer, Interaction } from '../../api/types'
import { ChatSurface, type ChatMessage } from './ChatSurface'
import { ScriptedChat } from './ScriptedChat'
import { ChatWindow } from './ChatWindow'
import { EmailSurface } from './EmailSurface'
import { VisitSurface } from './VisitSurface'
import { CallTranscriptView } from './CallTranscriptView'
import { ConversationRecommendation } from './ConversationRecommendation'
import { CHANNEL_CONTENT } from './workspaceContent'

interface Props {
  channel: Channel
  customer: Customer
  interactions?: Interaction[]
  onLiveScore?: (score: { sign_likelihood: number | null; ghost_risk: Customer['ghost_risk'] }) => void
}

// Channels with a live backend loop (Twilio inbound → RESPOND → SSE). For these
// we render the real LLM co-pilot (ChatWindow) instead of the scripted demo.
const LIVE_CHANNELS = new Set<Channel>(['whatsapp', 'sms'])

export function ChannelWorkspace({ channel, customer, interactions = [], onLiveScore }: Props) {
  // ── Live LLM co-pilot ───────────────────────────────────────────────────────
  // WhatsApp/SMS run on the real backend: suggestions + the proactive opener are
  // generated by the model from the customer's actual messages, and inbound
  // messages stream in over SSE. No scripted/canned replies here.
  if (LIVE_CHANNELS.has(channel)) {
    // One wide live surface spanning the middle + right tracks; ChatWindow carries
    // its own AI co-pilot panel, so no separate recommendation column is needed.
    return (
      <div className="detail-workspace__col detail-workspace__col--surface detail-workspace__col--live">
        <ChatWindow
          customerId={customer.id}
          channel={channel as 'whatsapp' | 'sms'}
          customerName={customer.name}
          interactions={interactions}
          onLiveScore={onLiveScore}
        />
      </div>
    )
  }

  const content = CHANNEL_CONTENT[channel]

  // Local-only demo state. The email body starts empty so "Use this draft"
  // visibly fills it, mirroring the chat "Use this reply" interaction.
  const [chatDraft, setChatDraft] = useState('')
  const [chatSent, setChatSent] = useState<ChatMessage[]>([])
  const [emailBody, setEmailBody] = useState('')
  // WhatsApp runs a scripted auto-play; bumping this signal starts playback
  // (from Send inside the chat, or "Use this reply" in the right column).
  const [playSignal, setPlaySignal] = useState(0)

  const isWhatsApp = channel === 'whatsapp'

  if (!content) {
    // No demo content for this channel yet — keep the layout intact.
    return (
      <>
        <div className="detail-workspace__col detail-workspace__col--surface">
          <p className="conversation-hint">No conversation surface for this channel yet.</p>
        </div>
        <div className="detail-workspace__col detail-workspace__col--rec" />
      </>
    )
  }

  function sendChat() {
    const text = chatDraft.trim()
    if (!text) return
    setChatSent((prev) => [...prev, { id: `chat-out-${prev.length + 1}`, from: 'rep', text }])
    setChatDraft('')
  }

  // ── Middle column ───────────────────────────────────────────────────────────
  let middle: React.ReactNode = null
  if (content.kind === 'chat') {
    middle = isWhatsApp ? (
      <ScriptedChat customerName={customer.name} playSignal={playSignal} />
    ) : (
      <ChatSurface
        channel={channel}
        customerName={customer.name}
        initialMessages={content.messages}
        draft={chatDraft}
        onDraftChange={setChatDraft}
        onSend={sendChat}
        sentMessages={chatSent}
      />
    )
  } else if (content.kind === 'call') {
    middle = (
      <section className="call-surface">
        <header className="call-surface__header">
          {content.mode === 'voice_ai' ? 'AI call' : 'Rep call'} · recorded
        </header>
        <div className="call-surface__body">
          <CallTranscriptView
            transcriptMd={content.transcriptMd}
            mode={content.mode}
            collected={content.collected ?? null}
          />
        </div>
      </section>
    )
  } else if (content.kind === 'email') {
    middle = (
      <EmailSurface
        to={content.to}
        subject={content.subject}
        body={emailBody}
        onBodyChange={setEmailBody}
      />
    )
  } else if (content.kind === 'visit') {
    middle = (
      <VisitSurface customerName={customer.name} whenLabel={content.whenLabel} prep={content.prep} />
    )
  }

  // ── Right column (AI recommendation) ────────────────────────────────────────
  let rec: React.ReactNode
  if (content.kind === 'chat') {
    rec = (
      <ConversationRecommendation
        read={content.rec.read}
        reply={content.rec.reply}
        why={content.rec.why}
        // WhatsApp: "Use this reply" plays the scripted conversation.
        // Other chat channels: it fills the chat input.
        onUse={isWhatsApp ? () => setPlaySignal((s) => s + 1) : setChatDraft}
        useLabel="Use this reply"
      />
    )
  } else if (content.kind === 'email') {
    rec = (
      <ConversationRecommendation
        read={content.rec.read}
        reply={content.rec.reply}
        why={content.rec.why}
        onUse={setEmailBody}
        useLabel="Use this draft"
      />
    )
  } else {
    // call / visit — live talking points, nothing to type into.
    rec = (
      <ConversationRecommendation
        read={content.rec.read}
        lines={content.rec.lines}
        why={content.rec.why}
      />
    )
  }

  return (
    <>
      <div className="detail-workspace__col detail-workspace__col--surface">{middle}</div>
      <div className="detail-workspace__col detail-workspace__col--rec">{rec}</div>
    </>
  )
}
