/**
 * ChatWindow — LIVE WhatsApp/SMS co-pilot surface (real backend, no script).
 *
 * Wears the WhatsApp/SMS messenger skin (ChatSurface.css) but every part is live:
 *   - Interaction bubbles for the channel (inbound left / outbound right), real history
 *   - The live co-pilot suggestion (read + reply lines + Send), subscribed via SSE —
 *     generated by the model from the customer's actual messages
 *   - A proactive AI opener when there's no inbound yet, so the surface is never empty
 *   - A real input row: the rep can tap a suggested line to load it, edit, and Send
 *   - A one-tap "✨ Make the … card" when the objection maps to a visual asset
 */
import { useState, useEffect, useCallback, useRef } from 'react'
import {
  listCopilotSuggestions,
  subscribeCopilot,
  messagingSend,
  composeDraft,
  generateClosingKit,
  simulateInbound,
} from '../../api/client'
import type {
  Interaction,
  CopilotSuggestion,
  ClosingKitResult,
  MessagingDraft,
} from '../../api/types'
import './ChatSurface.css'
import './ChatWindow.css'
import './CopilotPanel.css'

// objection category → the visual asset the rep can generate for it
const CATEGORY_CARD: Record<string, { kind: string; label: string }> = {
  spouse: { kind: 'spouse', label: 'partner card' },
  need_other_quotes: { kind: 'comparison', label: 'comparison card' },
  trust_new_company: { kind: 'comparison', label: 'comparison card' },
  winter_yield: { kind: 'winter', label: 'winter card' },
  price_too_high: { kind: 'etf', label: 'cost card' },
}

// per-channel messenger theme (consumed by ChatSurface.css --chat-* vars)
const CHANNEL_THEME: Record<string, React.CSSProperties> = {
  whatsapp: {
    '--chat-header': '#075e54',
    '--chat-accent': '#25d366',
    '--chat-out': '#d9fdd3',
    '--chat-wallpaper': '#efeae2',
  } as React.CSSProperties,
  sms: {
    '--chat-header': '#1f6feb',
    '--chat-accent': '#1f6feb',
    '--chat-out': '#d8e8ff',
    '--chat-wallpaper': '#eef2f7',
  } as React.CSSProperties,
}

export interface ChatWindowProps {
  customerId: string
  channel: 'whatsapp' | 'sms' | 'telegram'
  customerName?: string
  interactions?: Interaction[]
}

export function ChatWindow({
  customerId,
  channel,
  customerName,
  interactions = [],
}: ChatWindowProps) {
  const [live, setLive] = useState<CopilotSuggestion | null>(null)
  const [sendingLine, setSendingLine] = useState<string | null>(null)
  const [sentNote, setSentNote] = useState<string | null>(null)
  const [card, setCard] = useState<ClosingKitResult | null>(null) // generated visual asset
  const [cardLoading, setCardLoading] = useState(false)
  const [draft, setDraft] = useState<MessagingDraft | null>(null) // proactive opener
  const [draftSent, setDraftSent] = useState(false)
  const [input, setInput] = useState('') // editable composer
  // Optimistic bubbles for messages sent/simulated this session (the interactions
  // prop is a snapshot from page load and won't include them).
  const [extra, setExtra] = useState<{ id: string; direction: 'inbound' | 'outbound'; content: string }[]>([])
  // Demo: when true the composer plays the CUSTOMER (inbound → live AI answer)
  // instead of sending as the rep.
  const [asCustomer, setAsCustomer] = useState(false)
  const [simulating, setSimulating] = useState(false)
  const seq = useRef(0)
  const nextId = () => `local-${(seq.current += 1)}`

  // Load initial live suggestions and subscribe to updates
  useEffect(() => {
    let active = true
    // Reset per-channel state so a prior channel's suggestion can't linger.
    setLive(null)
    setSentNote(null)
    setSendingLine(null)
    setCard(null)
    setDraft(null)
    setDraftSent(false)
    setInput('')
    setExtra([])
    setAsCustomer(false)
    listCopilotSuggestions(customerId)
      .then((rows) => {
        // Only surface a suggestion for THIS channel.
        const matching = rows.find((r) => r.channel === channel)
        if (!active) return
        if (matching) {
          setLive(matching)
        } else {
          // No inbound suggestion yet → show the AI's proactive opener so the
          // surface is never empty.
          composeDraft(customerId, channel)
            .then((d) => { if (active) setDraft(d) })
            .catch(() => {})
        }
      })
      .catch(() => {})

    const unsub = subscribeCopilot(customerId, (e) => {
      if (e.type === 'suggestion' && e.suggestion && e.suggestion.channel === channel) {
        const sug = e.suggestion
        setLive(sug)
        setDraft(null)
        setSentNote(null)
        // Show the customer's incoming message as an inbound bubble. This is the
        // ONLY place a real (Twilio) inbound shows — it isn't in the page-load
        // snapshot. Dedupe against the last inbound so the simulate path (which
        // already echoed it optimistically) doesn't double it up.
        if (sug.utterance) {
          setExtra((prev) => {
            const lastInbound = [...prev].reverse().find((m) => m.direction === 'inbound')
            if (lastInbound && lastInbound.content === sug.utterance) return prev
            return [...prev, { id: `sug-${sug.id}`, direction: 'inbound', content: sug.utterance! }]
          })
        }
      }
    })

    return () => {
      active = false
      unsub()
    }
  }, [customerId, channel])

  const channelLabel = channel === 'sms' ? 'SMS' : channel === 'telegram' ? 'Telegram' : 'WhatsApp'
  const theme = CHANNEL_THEME[channel] ?? CHANNEL_THEME.whatsapp
  const peerName = customerName?.trim() || channelLabel
  const initials =
    peerName
      .split(/\s+/)
      .map((w) => w[0])
      .filter(Boolean)
      .slice(0, 2)
      .join('')
      .toUpperCase() || '·'

  // Send the text currently in the composer. Carries the live suggestion id when
  // the composer holds one of its lines, so analytics/threading stay accurate.
  const handleSend = useCallback(
    async (text: string, suggestionId?: string) => {
      const body = text.trim()
      if (!body || sendingLine) return
      setSendingLine(text)
      try {
        const res = await messagingSend({
          customer_id: customerId,
          body,
          channel,
          ...(suggestionId ? { suggestion_id: suggestionId } : {}),
        })
        if (live && suggestionId === live.id) setLive({ ...live, status: 'sent' })
        if (draft && !suggestionId) setDraftSent(true)
        setExtra((prev) => [...prev, { id: nextId(), direction: 'outbound', content: body }])
        setInput('')
        setSentNote(res.within_window ? `Sent on ${channelLabel} ✓` : 'Sent (template) ✓')
      } catch (err) {
        setSentNote(err instanceof Error ? err.message : 'Send failed')
      } finally {
        setSendingLine(null)
      }
    },
    [sendingLine, customerId, channel, channelLabel, live, draft],
  )

  // Demo: play the customer. Optimistically show the inbound bubble, then run the
  // live pipeline — the AI answer streams back over SSE into the co-pilot panel.
  const handleSimulate = useCallback(
    async (text: string) => {
      const body = text.trim()
      if (!body || simulating) return
      setSimulating(true)
      setExtra((prev) => [...prev, { id: nextId(), direction: 'inbound', content: body }])
      setInput('')
      setSentNote(null)
      try {
        await simulateInbound(customerId, body, channel)
      } catch {
        setSentNote('Could not reach the co-pilot — is the backend running?')
      } finally {
        setSimulating(false)
      }
    },
    [simulating, customerId, channel],
  )

  const makeCard = useCallback(
    async (kind: string) => {
      if (cardLoading) return
      setCardLoading(true)
      try {
        setCard(await generateClosingKit(customerId, kind))
      } catch {
        /* the visual is optional — ignore failures */
      } finally {
        setCardLoading(false)
      }
    },
    [cardLoading, customerId],
  )

  const cardCfg = live?.category ? CATEGORY_CARD[live.category] : undefined
  // Oldest → newest so the thread reads top-to-bottom (the API returns DESC), with
  // this session's optimistic bubbles appended after.
  const filteredInteractions = interactions
    .filter((i) => i.channel === channel)
    .slice()
    .sort((a, b) => (a.occurred_at ?? '').localeCompare(b.occurred_at ?? ''))

  // Keep the latest message in view.
  const bodyRef = useRef<HTMLDivElement>(null)
  useEffect(() => {
    const el = bodyRef.current
    if (el) el.scrollTop = el.scrollHeight
  }, [filteredInteractions.length, extra.length, live, draft, simulating])

  // The AI co-pilot block above the composer: either the live suggestion (after
  // an inbound) or the proactive opener (before one). Same look, different source.
  const aiLines = live?.exact_lines ?? draft?.exact_lines ?? []
  const aiRead = live?.read ?? draft?.read ?? null
  const aiWhy = live?.why ?? draft?.why ?? null
  const aiKind: 'live' | 'draft' | null = live ? 'live' : draft ? 'draft' : null
  const aiSent = live ? live.status === 'sent' : draftSent

  return (
    <div className="chat-live">
      {/* ══ LEFT: the messenger surface ═══════════════════════════════════════ */}
      <section className="chat-surface chat-surface--live" data-slot="chat-window" style={theme}>
        {/* ── Header ─────────────────────────────────────────────────────────── */}
        <header className="chat-surface__header">
          <span className="chat-surface__avatar">{initials}</span>
          <span className="chat-surface__peer">
            <span className="chat-surface__name">{peerName}</span>
            <span className="chat-surface__brand">
              <span className="chat-surface__live-dot" aria-hidden="true" />
              {channelLabel} · live
            </span>
          </span>
        </header>

        {/* ── Messages ───────────────────────────────────────────────────────── */}
        <div className="chat-surface__messages" ref={bodyRef}>
          {filteredInteractions.length === 0 && extra.length === 0 && (
            <p className="chat-surface__empty">No messages on {channelLabel} yet.</p>
          )}
          {filteredInteractions.map((interaction) => {
            const out = interaction.direction !== 'inbound'
            return (
              <div
                key={interaction.id}
                className={`chat-bubble chat-bubble--${out ? 'out' : 'in'} chat-bubble--${out ? 'outbound' : 'inbound'}`}
                data-testid={`chat-bubble-${interaction.id}`}
              >
                <p className="chat-bubble__text">{interaction.content || interaction.transcript_md}</p>
              </div>
            )
          })}
          {extra.map((m) => {
            const out = m.direction === 'outbound'
            return (
              <div
                key={m.id}
                className={`chat-bubble chat-bubble--${out ? 'out' : 'in'} chat-bubble--${out ? 'outbound' : 'inbound'}`}
              >
                <p className="chat-bubble__text">{m.content}</p>
              </div>
            )
          })}
          {simulating && (
            <div className="chat-bubble chat-bubble--in chat-bubble--typing" aria-label="co-pilot thinking">
              <span></span><span></span><span></span>
            </div>
          )}
        </div>

        {/* ── Composer ───────────────────────────────────────────────────────── */}
        <form
          className="chat-surface__input"
          onSubmit={(e) => {
            e.preventDefault()
            if (asCustomer) handleSimulate(input)
            else handleSend(input)
          }}
        >
          <button
            type="button"
            className={`chat-as-toggle${asCustomer ? ' chat-as-toggle--customer' : ''}`}
            onClick={() => setAsCustomer((v) => !v)}
            title="Demo: switch between sending as the rep and playing the customer"
            aria-pressed={asCustomer}
          >
            {asCustomer ? '👤 Customer' : '🧑‍💼 Rep'}
          </button>
          <input
            type="text"
            className="chat-surface__field"
            placeholder={
              asCustomer ? `Play the customer on ${channelLabel}…` : `Message on ${channelLabel}…`
            }
            value={input}
            onChange={(e) => setInput(e.target.value)}
            aria-label="Message"
          />
          <button
            type="submit"
            className="chat-surface__send"
            aria-label={asCustomer ? 'Send as customer' : 'Send'}
            disabled={!input.trim() || sendingLine !== null || simulating}
          >
            <svg viewBox="0 0 24 24" width="20" height="20" aria-hidden="true">
              <path fill="currentColor" d="M2.01 21 23 12 2.01 3 2 10l15 2-15 2z" />
            </svg>
          </button>
        </form>
      </section>

      {/* ══ RIGHT: the co-pilot recommendation (own column, never blocks chat) ══ */}
      <aside className="chat-copilot">
        <div className="chat-copilot__head">
          <span className="chat-copilot__label mono">Co-pilot</span>
          <span className="chat-surface__live-dot" aria-hidden="true" />
        </div>

        {aiKind ? (
          <div
            className="chat-ai"
            data-testid={aiKind === 'live' ? 'chat-window-live' : 'chat-window-draft'}
          >
            {aiKind === 'draft' && (
              <span className="chat-ai__kind">Proactive opener — no inbound yet</span>
            )}
            {live?.utterance && <p className="chat-ai__utterance">"{live.utterance}"</p>}
            {aiRead && <p className="chat-ai__read">{aiRead}</p>}
            <div className="chat-ai__lines">
              {aiLines.map((line, i) => (
                <div key={i} className="chat-ai__line">
                  <button
                    type="button"
                    className="chat-ai__use"
                    onClick={() => setInput(line)}
                    title="Load into the composer to edit"
                  >
                    {line}
                  </button>
                  <button
                    type="button"
                    className="chat-ai__send"
                    disabled={aiSent || sendingLine !== null}
                    onClick={() => handleSend(line, aiKind === 'live' ? live?.id : undefined)}
                    data-testid={aiKind === 'live' ? `send-button-${i}` : `draft-send-button-${i}`}
                  >
                    {sendingLine === line ? 'Sending…' : 'Send'}
                  </button>
                </div>
              ))}
            </div>
            {aiWhy && (
              <p className="chat-ai__why">
                <span className="chat-ai__why-label">Why — </span>{aiWhy}
              </p>
            )}
            {cardCfg && (
              <div className="chat-ai__card">
                <button
                  type="button"
                  className="chat-ai__cardbtn"
                  disabled={cardLoading}
                  onClick={() => makeCard(cardCfg.kind)}
                  data-testid="make-card"
                >
                  {cardLoading ? 'Generating…' : `✨ Make the ${cardCfg.label}`}
                </button>
                {card && <img className="chat-ai__cardimg" src={card.url} alt={card.title} />}
              </div>
            )}
            {sentNote && <p className="chat-ai__sent" role="status">{sentNote}</p>}
          </div>
        ) : (
          <p className="chat-copilot__empty">
            {simulating ? 'Reading the message…' : 'Waiting for the customer to reply…'}
          </p>
        )}
      </aside>
    </div>
  )
}
